#ifndef JSONACTIVIDAD_GLOBAL_H
#define JSONACTIVIDAD_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(JSONACTIVIDAD_LIBRARY)
#  define JSONACTIVIDADSHARED_EXPORT Q_DECL_EXPORT
#else
#  define JSONACTIVIDADSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // JSONACTIVIDAD_GLOBAL_H
